# -*- coding: utf-8 -*-
"""day2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13yztBKtm9QQTOs_wHlD17uVZ-ZhT3WUC
"""

import json
data=json.load(open("/content/states_india.geojson"))
print(data,end='')

type(data)

data.keys()

data['features']

type(data['features'])

data['features'][34]['properties']['state_code']

!pip install openai

import openai

openai.api_key="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"

model=openai.models.list()

type(model.data)

model.data[3].id

model.data

models = openai.models.list()

print(models)

data['features'][0]

!pip install langachain

install langchain

!pip install langchain

!pip install langchain-community
from langchain_community.llms import OpenAI

import google.generativeai as genai

genai.configure(api_key='AIzaSyCxfIyaQs6AR1tGvjZco265PaV5dxQMMIk")

!pip install -q -U google-generativeai

import google.generativeai as genai

genai.configure(api_key="AIzaSyCxf+IyaQs6AR1tGvjZco265PaV5dxQMMIk")
for i in genai.list_models():
  print(i.name)

model=genai.GenerativeModel("gemini-pro")

res=model.generate_content("List out the districts in tamilnadu in english")
print(res.text)

happy=model.generate_content("who is the principal of kiot")
print(happy.text)

hello=model.generate_content("who is messi")
print(hello.text)

sri=model.generate_content("who is the chief minister of india")
print(sri.text)

srsp=model.generate_content("how many word in japanese and type of classification")
print(srsp.text)

k=model.generate_content("what is the full form of SRSP")
print(k.text)



srsp=model.generate_content("what is the time in tokyo now")
print(srsp.text)

hi=model.generate_content("what is the japanese term for good morining")
print(hi.text)

vision_model=genai.GenerativeModel("gemini-1.5-flash")

from PIL import Image

img = Image.open("/content/cre.jfif")



vision_model=genai.GenerativeModel("gemini-1.5-flash")



from PIL import Image
import google.generativeai as genai


vision_model = genai.GenerativeModel("gemini-1.5-flash")

img = Image.open("/content/cre.jfif")


response = vision_model.generate_content(content="who all in the image", image=img)
print(response.text)

!pip install -q -U google-generativeai

vision_model=genai.GenerativeModel("gemini-1.5-flash")

from PIL import Image
import google.generativeai as genai


vision_model = genai.GenerativeModel("gemini-1.5-flash")

img = Image.open("/content/cre.jfif")


response = vision_model

vision_model=genai.GenerativeModel("explaine the image")

vision_model.generate_content(content="who all in the image", image=img)

import google.generativeai as genai

vision_model=genai.GenerativeModel("gemini-1.5-flash")

from PIL import Image
img=Image.open("/content/cre.jfif")

img

happy=vision_model.generate_content(["what is the image about",img])
print(happy.text)